### ISSUE TITLE
Manually compiling with traceur produces different output

### ISSUE THREAD

**Issue by jamesandres** [sindresorhus/gulp-traceur#10]
Hello,

There is a decent chance I'm doing it wrong, but it's worth a bug report anyway I think :).

If I compile a simple this simple ES6 module with traceur 0.0.31 directly I get significantly different output than when using gulp-traceur.

On a simple static HTML test page (with the traceur-runtime.js of course) the manually compiled version seems to work great. The gulp-traceur version I have not been able to get running.

**core/thing.js**
```javascript
export class Thing {
    constructor(config) {
        console.log("Thing loaded.");
    }
}
```

**app.js**
```javascript
import { Thing } from './core/thing'


export class App {
    constructor(config) {
        this.thing = Thing()
        console.log("Yip, I'm here.");
    }
}
```

**traceur --out manual-build.js app.js core/thing.js**
```javascript
System.register("core/thing", [], function() {
  "use strict";
  var __moduleName = "core/thing";
  var Thing = function Thing(config) {
    console.log("Thing loaded.");
  };
  ($traceurRuntime.createClass)(Thing, {}, {});
  return {get Thing() {
      return Thing;
    }};
});
System.register("app", [], function() {
  "use strict";
  var __moduleName = "app";
  var Thing = System.get("core/thing").Thing;
  var App = function App(config) {
    this.thing = Thing();
    console.log("Yip, I'm here.");
  };
  ($traceurRuntime.createClass)(App, {}, {});
  return {get App() {
      return App;
    }};
});
System.get("app" + '');
System.get("core/thing" + '');
```

**gulp**
```javascript
"use strict";
var __moduleName = "thing";
var Thing = function Thing(config) {
  console.log("Thing loaded.");
};
($traceurRuntime.createClass)(Thing, {}, {});
module.exports = {
  get Thing() {
    return Thing;
  },
  __esModule: true
};

"use strict";
var __moduleName = "app";
var Thing = require('./core/thing').Thing;
var App = function App(config) {
  this.thing = Thing();
  console.log("Yip, I'm here.");
};
($traceurRuntime.createClass)(App, {}, {});
module.exports = {
  get App() {
    return App;
  },
  __esModule: true
};

"use strict";
var __moduleName = "section_nav_controller";
```

**index.html (test file)**
```html
<!DOCTYPE html>
<html>
<head>
    <title>Test</title>

    <script src="libs/traceur-runtime/traceur-runtime.js"></script>

    <script type="text/javascript" src="manual-build.js"></script>
</head>
<body>
    <script>
        var config = {
        };

        console.log("Inside the script module.");

        // Bizarre module fetching syntax from the traceur compiler..
        var App = System.get("../app/app").App;

        window.app = new App(config);
    </script>
</body>
</html>
```

**Comment by SekibOmazic** [comment]
My cheap workaround until this is resolved (requires gulp-shell, and traceur installed globally):

gulp.task('traceur-from-shell', function () {
  return gulp.src(es6Sources)
    .pipe(shell(['traceur --out dist.js es6/*/*.js']))
});

**Comment by juancabrera** [comment]
@SekibOmazic there is already a gulp plugin for that https://www.npmjs.org/package/gulp-traceur-cmdline

**Comment by SekibOmazic** [comment]
@juancabrera Yes, I'm aware of it but it didn't work form me for 2 reasons. First I couldn't launch traceur due to: ```traceurcmd: __dirname + "/node_modules/traceur/traceur"```(Threw "No such file or directory") and after manually fixing it didn't merge multiple input files into one output file but took just last one.

Anyhow, we should move this discussion to your project because it doesn't belong here ;-)

**Comment by juancabrera** [comment]
@SekibOmazic word, fell free to create an issue.

**Comment by origin1tech** [comment]
@SekibOmazic did u try gulp-traceur-compiler ? It does exactly what you're looking for. It builds the output exactly as traceur cli does.

Something to think about though and why I think @sindresorhus is not eager to add this feature, is that when you output to single file you're kind of going away from the principal of imports via System.register/import.

Say you have a lib of helpers if you output to single file and u use that helper lib multiple times you'll end up with it exported into each file with a system.register call.

Anyway the more I play with ES6 stuff the more I feel its better to leave the directory structure and simply compile it. 

Just my .02.
