### ISSUE TITLE
Single file build

### ISSUE THREAD

**Issue by guybedford** [sindresorhus/gulp-traceur#17]
Traceur provides the ability to trace a single file and build all of its dependencies into one file. I'm not sure if that would make sense or not for this plugin.

One API for using this is described here - https://github.com/aaronfrost/grunt-traceur/issues/21#issue-32564555.

Thinking further about this, it seems to go against the principles of gulp though so perhaps we should ignore this?

**Comment by sindresorhus** [comment]
Relevant grunt-traceur discussion: https://github.com/aaronfrost/grunt-traceur/issues/21#issuecomment-52718085

**Comment by sindresorhus** [comment]
Traceur ticket: https://github.com/google/traceur-compiler/issues/1626

**Comment by aleemb** [comment]
@sindresorhus @davidjnelson any update on this would be swell.

**Comment by sindresorhus** [comment]
This package is deprecated now as Traceur is unmaintained.
