### ISSUE TITLE
[feature proposal] allow functions in the moduleName option

### ISSUE THREAD

**Issue by pkozlowski-opensource** [sindresorhus/gulp-traceur#54]
Today I needed to hand-craft a gulp plugin similar to this one as I needed to dynamically calculate a module name (`moduleName` option) based on the input file path. 

Would you be open to suggestion of supporting `moduleName` being a function that would be executed with the input file path (or the whole vinyl file) to calculate module name as string?

**Comment by sindresorhus** [comment]
Why? What's your use-case for needing that?

**Comment by pkozlowski-opensource** [comment]
You need a module name(s) to be able to be able pre-load modules outputted by traceur's `instantiate` module format. I might want to generate different modules, ex.: based on the folder name and then pre-load some of the modules. 

Obviously I could duplicate `gulp.src('foldername/**/*.js').pipe('traceur({moduleName: 'foldername'})'` for each folder in my project but a function to "calculate" a module name would solve it more elegantly, IMO.

What would you propose as an alternative solution in this case? 

Relevant discussion in https://github.com/systemjs/systemjs/issues/300

**Comment by sindresorhus** [comment]
Yeah, good point. I'm not sure it's possible to implement this here though as we need to reuse the Traceur compiler instance for all files https://github.com/sindresorhus/gulp-traceur/commit/3b4935ece473c73a29c46bdbc2d00a81c3b1fd5d and the options are passed in the constructor. Suggestions welcome.

**Comment by rochejul** [comment]
+1

I am in a similar case :)

Here a function I have made for my process (maybe the moduleName option can be a function):

function _traceurGulpStream() {
    return through2.obj(function (file, enc, cb) {
        var
            filePath = file.path.substr(options.dirname.length + 1), // To be on the root folder
            filename = filePath.substr(4), // To be on the src folder
            compiler = new traceur.NodeCompiler({
                'experimental': true,
                'modules': 'instantiate',
                'moduleName': filename.substr(0, filename.length - 3)
            }),
            inputFilePath = compiler.normalize(filePath);

        try {
            file.contents = new Buffer(compiler.write(
                compiler.transform(
                    compiler.parse(
                        fs.readFileSync(file.path).toString(),
                        inputFilePath
                    ),
                    undefined,
                    inputFilePath
                ),
                inputFilePath
            ));

            this.push(file);
            cb();

        } catch (e) {
            this.emit('error', new gutil.PluginError('gulp-traceur', 'Exit code with ' + e));
            this.push(file);
            cb();
        }
    });
}

**Comment by zzo** [comment]
+1 to this I also need to calculate the moduleName and not sure how to do this from within gulp using pipe.

**Comment by sindresorhus** [comment]
This package is deprecated now as Traceur is unmaintained.
