### ISSUE TITLE
Experimental options - async/await

### ISSUE THREAD

**Issue by hendrikswan** [sindresorhus/gulp-traceur#60]
I specifically want to use traceur to use async/await. As far as I understand, this needs to be enabled by passing experimental flag to traceur. 

Over here https://github.com/sindresorhus/gulp-traceur#traceuroptions it states that you should just pass whatever options you want to pass to the traceur compiler to the constructor of the gulp-traceur task. As you can see, I did this in my setup. 

```javascript
gulp.task('trac', function () {
    return gulp.src('./scripts/**/*.js')
        .pipe(traceur({experimental: true}))
        .on('error', function (err) {
          console.error('Error', err.message);
        })        
        .pipe(sourcemaps.init())
        .pipe(sourcemaps.write())
        .pipe(gulp.dest('./dist/js')); 
});
```

To test the setup, I copied this code I found on the interwebs into my files: 

```javascript
function promisingOperation() {
    return new Promise(function(resolve, reject) {
        setTimeout(function() {
            if( Math.round(Math.random()) ){
                resolve('Success!');
            }
            else{
                reject('Failure!');
            }
        }, 1000);
    });
}
 
(async function () {
    var message = await promisingOperation();
    console.log(message);
})(); 
```

But when the gulp task runs, it gives me this output: 

`Error filename:line:char: Semi-colon expected`, which points to just after the `await` statement. 
So it seems to me like it's not enabling the experimental features correctly?

**Comment by sindresorhus** [comment]
This task just passes options to Traceur: https://github.com/sindresorhus/gulp-traceur/blob/dbef4ad745b555ead5c171c612d7c7510f16c644/index.js#L9

If it's not working that's a Traceur issue and should be opened on its issue tracker instead ;)

**Comment by hendrikswan** [comment]
Thanks Sindre.

**Comment by hendrikswan** [comment]
For anyone else struggling with this, I've opened an issue on the traceur repo: https://github.com/google/traceur-compiler/issues/1711
