### ISSUE TITLE
Input sourceMaps not forwarded to traceur

### ISSUE THREAD

**Issue by joIivier** [sindresorhus/gulp-traceur#65]
I use gulp-sourcemaps but the sourceMaps my files have are not transmitted to traceur.

From traceur source code, we read the input source maps from the options https://github.com/google/traceur-compiler/blob/master/src/Compiler.js#L224 but this option is not populated as in gulp-traceur we create the compiler before receiving files.

I fixed my build by removing the early creation of the compiler and changed [this line](https://github.com/sindresorhus/gulp-traceur/blob/master/index.js#L23) this way:
```javascript
var compiler = new traceur.NodeCompiler(objectAssign({modules: 'commonjs', inputSourceMap: file.sourceMap}, opts));
var ret = compiler.compile(file.contents.toString(), file.relative, file.relative, file.base);
```

I am using traceur 0.0.87 and gulp-traceur 0.17.0

**Comment by kevva** [comment]
Thanks for reporting, should be fixed now.

**Comment by joIivier** [comment]
Thanks for the super fast fix!

**Comment by kevva** [comment]
Just wondering, how come that it worked in the tests before this fix? Are you doing something special?

**Comment by joIivier** [comment]
I don't see in your test suite a test for my situation when there is a sourceMap in the file before giving it to traceur, so that might be a reason :). 
I have a JSX transpilation before traceur, in this must be pretty rare yet since even in traceur itself I have unresolved issues with these input sourceMaps ^^ (https://github.com/google/traceur-compiler/issues/1799).

**Comment by szkrd** [comment]
I couldn't find a release schedule: when will the version be bumped to 0.18? The broken sourcemap output is quite cumbersome.
