### ISSUE TITLE
Mapped error stack traces

### ISSUE THREAD

**Issue by zdychacek** [sindresorhus/gulp-traceur#66]
Hi,
is there any way to get mapped stack traces when error is thrown?

I tried following example code and ended with source maps generated, but it would be nice if these source maps could be used to map error stack traces to original locations. Is there any way to achieve that?

I read this [article](http://www.2ality.com/2015/04/node-es6-transpiled.html) describing how to achieve that with babel transpiler. I tried the same with traceur but it didn't work.

```
gulp.task('default', function () {
    return gulp.src('src/*.js')
        .pipe(sourcemaps.init())
        .pipe(traceur())
        .pipe(sourcemaps.write('.'))
        .pipe(gulp.dest('dist'));
});
```

Thanks for reply.

**Comment by sindresorhus** [comment]
That should be handled by Traceur, not this plugin.

https://github.com/google/traceur-compiler/issues
