### ISSUE TITLE
Unexpected reserved word import

### ISSUE THREAD

**Issue by jklue** [sindresorhus/gulp-traceur#70]
I'm trying to use the import feature in ES6 and use a Google material design component in my website. In my scripts.js file I have
`import {MDCDialog, MDCDialogFoundation, util} from '@material/dialog';`

**[EDIT]** When I run traceur in gulp I get the following error:
```
MultipleErrors in plugin 'gulp-traceur' Message:
scripts.js:1188:5: Unexpected reserved word import
scripts.js:1188:12: Semi-colon expected
```

What am I doing wrong? Thank you!

**Comment by sindresorhus** [comment]
This package is deprecated now as Traceur is unmaintained.
